#!/bin/bash

#Grab the mysql credentials from the config file.
#Adapted from Daves civi install script

#>brisskit_db_param name|user|pass database
#e.g. >brisskit_db_pass redcap pass
#to get the mysql password for the redcap DB

#12/4/12

#Make sure there was an input
if [ -n "$1" ]
then
    database=$1
    conf="/etc/brisskit/mysql/${database}.cfg"
    
    #Make sure the file exists
    if [ ! -f "$conf" ]
    then
	echo "ERROR. $conf does not exist"
    fi
else
    echo "Error. No DB name given."
    exit
fi


if [ -n "$2" ]
then
    field=$2
    sed -n 's/^'"${field}"'=\(.\{1,\}\)$/\1/p' "${conf}"
else
    echo "Error. No field given, expecting name|user|pass"
fi
