class users::hack
{
        realize( Users::Virtual::Ssh_user["temp"] )
	realize( Users::Virtual::Ssh_user["temp"] )
	realize( Users::Virtual::Ssh_user["adrianm"] )
	realize( Users::Virtual::Ssh_user["adamr"] )
	realize( Users::Virtual::Ssh_user["adamw"] )
	realize( Users::Virtual::Ssh_user["andrewl"] )
	realize( Users::Virtual::Ssh_user["andyc"] )
	realize( Users::Virtual::Ssh_user["anthonyt"] )
	realize( Users::Virtual::Ssh_user["christianam"] )
	realize( Users::Virtual::Ssh_user["christianb"] )
	realize( Users::Virtual::Ssh_user["davem"] )
	realize( Users::Virtual::Ssh_user["daphnec"] )
	realize( Users::Virtual::Ssh_user["fangmins"] )
	realize( Users::Virtual::Ssh_user["gerritw"] )
	realize( Users::Virtual::Ssh_user["jang"] )
	realize( Users::Virtual::Ssh_user["jenss"] )
	realize( Users::Virtual::Ssh_user["jonathant"] )
	realize( Users::Virtual::Ssh_user["jonathanr"] )
	realize( Users::Virtual::Ssh_user["karinem"] )
	realize( Users::Virtual::Ssh_user["kirstyp"] )
	realize( Users::Virtual::Ssh_user["mahendram"] )
	realize( Users::Virtual::Ssh_user["malcolmn"] )
	realize( Users::Virtual::Ssh_user["malcolmt"] )
	realize( Users::Virtual::Ssh_user["martinh"] )
	realize( Users::Virtual::Ssh_user["neilb"] )
	realize( Users::Virtual::Ssh_user["nickh"] )
	realize( Users::Virtual::Ssh_user["paulm"] )
	realize( Users::Virtual::Ssh_user["richarda"] )
	realize( Users::Virtual::Ssh_user["robf"] )
	realize( Users::Virtual::Ssh_user["simonh"] )
	realize( Users::Virtual::Ssh_user["srikantha"] )
	realize( Users::Virtual::Ssh_user["timb"] )
	realize( Users::Virtual::Ssh_user["titoc"] )
	realize( Users::Virtual::Ssh_user["veerlee"] )
}
