#!/bin/bash

#Nagios plugin to check the output of clamscan

#Grab the library.
. /usr/lib/nagios/plugins/utils.sh


logfile="/var/log/clamav/scan.log"

#Check log file exists
if [ ! -f "$logfile" ]
then
	echo "Log file not present"
	exit $STATE_UNKNOWN
fi

#Check if log file is zero size - when a scan starts it remakes it,
#so nagios starts to think there is a virus.
if [ ! -s "$logfile" ]
then
   	#Check age of log file - if its been empty for a day then its not doing a scan!
        if test `find "$logfile" -mtime +1`
        then
		echo "Log file has been empty for a long time - scan in progress?"
		exit $STATE_UNKNOWN
	fi
	
 	echo "OK - probably doing a scan."
        exit $STATE_OK

fi


#Check age of log file
if test `find "$logfile" -mtime +8`
then
	echo "Log file is out of date!"
	exit $STATE_WARNING
fi

#Search for the number of infected files
if test `grep --count "Infected files: 0" $logfile` != 1
then
	echo "Virus found!"
	exit $STATE_CRITICAL
fi

#If we get to here then everything must be ok :)
echo "OK - no viruses found. Scanned on `date -r $logfile`"
exit $STATE_OK


